    stratum_port:   ":5555"
    hcp:            ":5556"
    kaspad_address: kaspad-service.default:16110
    redis_port:     ":6379"
    postgres:
      host:         postgres.data
      port:         5432
      user:         pooladmin
      pass:         a0R4Jk10MG1qODg5NEFecEMxWGlQdFp1OTFESEJwUWU5cyF1R0k2RA
      database:     kaspa-db